select *
FROM PortfoiloProject..COVIDDEATHS
ORDER BY 3,4 


SELECT 
LOCATION, 
DATE,
TOTAL_CASES,
NEW_CASES,
TOTAL_DEATHS,
POPULATION
FROM PortfoiloProject..COVIDDEATHS
ORDER BY 1,2

--LOOKING AT TOTAL_CASES vs TOTAL_DEATHS
SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 AS DeathsPercentage
FROM PortfoiloProject..COVIDDEATHS
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1,2

--LOOKING AT TOTAL CASES vs POPULATION

SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_CASES/POPULATION)*100 AS PercentagePopulationInfected
FROM PortfoiloProject..COVIDDEATHS
ORDER BY 1,2

-- LOOKING AT COUNTRIES WITH THE HIGHEST INFFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HighestInfectionCount, MAX(TOTAL_CASES/POPULATION)*100 AS PercentagePopulationInfected
FROM PortfoiloProject..COVIDDEATHS

GROUP BY LOCATION, POPULATION
ORDER BY PercentagePopulationInfected DESC

-- SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT

SELECT LOCATION, MAX(cast(TOTAL_DEATHS as int)) AS TotalDeathCount
FROM PortfoiloProject..COVIDDEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TotalDeathCount DESC

-- LETS BREAK DOWN BY CONTINENTS

SELECT LOCATION, MAX(cast(TOTAL_DEATHS as int)) AS TotalDeathCount
FROM PortfoiloProject..COVIDDEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TotalDeathCount DESC

-- GLOBAL NUMBERS

SELECT  SUM(new_cases) AS Total_CASES, 
SUM(CAST(NEW_DEATHS AS INT)) AS Total_DEATHS,
SUM(CAST(NEW_DEATHS AS INT))/SUM(new_cases)* 100 AS DeathPercentage
FROM PortfoiloProject..COVIDDEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

--LOOKING AT TOTAL POPULATION vs VACCINATIONS

SELECT dea.CONTINENT, dea.LOCATION, dea.DATE, dea.POPULATION, vac.NEW_VACCINATIONS,
SUM(CONVERT(INT,vac.NEW_VACCINATIONS)) OVER (PARTITION BY dea.LOCATION ORDER BY dea.LOCATION, dea.DATE) AS RollingPeopleVaccinated
-- ,(RollingPeopleVaccinated/population)*100
FROM PortfoiloProject..COVIDDEATHS dea
join PortfoiloProject..COVIDVACCINATIONS vac
ON dea.LOCATION = vac.LOCATION
AND dea.DATE = vac.DATE
WHERE dea.CONTINENT IS NOT NULL 
ORDER BY 2,3

-- USE CTE

WITH PopvsVac(CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, RollingPeopleVaccinated)
AS
(
SELECT dea.CONTINENT, dea.LOCATION, dea.DATE, dea.POPULATION, vac.NEW_VACCINATIONS,
SUM(CONVERT(INT,vac.NEW_VACCINATIONS)) OVER (PARTITION BY dea.LOCATION ORDER BY dea.LOCATION, dea.DATE) AS RollingPeopleVaccinated
-- ,(RollingPeopleVaccinated/population)*100
FROM PortfoiloProject..COVIDDEATHS dea
join PortfoiloProject..COVIDVACCINATIONS vac
ON dea.LOCATION = vac.LOCATION
AND dea.DATE = vac.DATE
WHERE dea.CONTINENT IS NOT NULL 
ORDER BY 2,3
)
SELECT *, (RollingPeopleVaccinated/POPULATION)*100
FROM PopvsVAC

-- TEMP TABLE

DROP TABLE IF EXISTS #PercentPopulationVaccinated
CREATE TABLE #PercentPopulationVaccinated
(
CONTINENT nvarchar(255),
LOCATION nvarchar(255),
DATE datetime,
POPULATION numeric,
NEW_VACCINATIONS numeric,
RollingPeopleVaccinated numeric
)

INSERT INTO #PercentPopulationVaccinated
SELECT dea.CONTINENT, dea.LOCATION, dea.DATE, dea.POPULATION, vac.NEW_VACCINATIONS,
SUM(CONVERT(INT,vac.NEW_VACCINATIONS)) OVER (PARTITION BY dea.LOCATION ORDER BY dea.LOCATION, dea.DATE) AS RollingPeopleVaccinated
FROM PortfoiloProject..COVIDDEATHS dea
join PortfoiloProject..COVIDVACCINATIONS vac
ON dea.LOCATION = vac.LOCATION
AND dea.DATE = vac.DATE

SELECT *,RollingPeopleVaccinated*100
FROM #PercentPopulationVaccinated

--CREATING VIEW TO STORE DATA FOR LATER VISUALIZATIONS

CREATE VIEW PercentPopulationVaccinated AS
SELECT dea.CONTINENT, dea.LOCATION, dea.DATE, dea.POPULATION, vac.NEW_VACCINATIONS,
SUM(CONVERT(INT,vac.NEW_VACCINATIONS)) OVER (PARTITION BY dea.LOCATION ORDER BY dea.LOCATION, dea.DATE) AS RollingPeopleVaccinated
FROM PortfoiloProject..COVIDDEATHS dea
join PortfoiloProject..COVIDVACCINATIONS vac
ON dea.LOCATION = vac.LOCATION
AND dea.DATE = vac.DATE
WHERE dea.CONTINENT IS NOT NULL 

SELECT *

FROM PercentPopulationVaccinated
